#!/usr/bin/env python3
"""Generate the derived token files from design/tokens.json:
  .streamlit/config.toml (theme values)  ·  design/tokens.css  ·  rust/fxradar-serve/static/tokens.json
Run after editing tokens.json (`make tokens`); the outputs are committed."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from fxradar import tokens as tk  # noqa: E402

CONFIG = f"""# GENERATED by scripts/gen_tokens.py from design/tokens.json — edit the tokens, not this file.
[theme]
base = "dark"
primaryColor = "{tk.ACCENT}"            # beacon: links / actions (regime colours are data-only)
backgroundColor = "{tk.BG}"         # nimbus
secondaryBackgroundColor = "{tk.SURFACE}" # front: cards / sidebar
textColor = "{tk.TEXT}"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
"""


def main() -> None:
    (ROOT / ".streamlit" / "config.toml").write_text(CONFIG)
    (ROOT / "design" / "tokens.css").write_text(
        f"@import url('{tk.FONT_IMPORT}');\n{tk.css_variables()}\n"
    )
    static = ROOT / "rust" / "fxradar-serve" / "static"
    if static.exists():
        (static / "tokens.json").write_text(
            json.dumps(
                {
                    "regime": tk.REGIME_COLORS,
                    "surface": tk.TOKENS["surface"],
                    "text": tk.TOKENS["text"],
                    "accent": tk.TOKENS["accent"],
                },
                indent=1,
            )
        )
    print(
        "wrote .streamlit/config.toml, design/tokens.css"
        + (", rust static tokens.json" if static.exists() else "")
    )


if __name__ == "__main__":
    main()
