#!/usr/bin/env python3
"""Seed config/visual_registry.yaml — the fifty cards of docs/REGISTRY-50.md (phase 38).

One shape for all fifty entries, so a card is never bespoke code: id, status, tier, family,
primitive, question_intents (EN/DE/FR), args (enums and key references only — NEVER a numeric
type), bindings (dotted artifact paths), disambiguation, caption/aria templates, when_not and
owner_artifact. Run once to seed; after that the YAML is the source of truth and is edited by hand.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "visual_registry.yaml"
REGISTRY_VERSION = "3.0.0"

PACK = "data/avatar_context.json"
TRE = "data/treasury_risk.json"
DEC = "data/decision_table.json"
STATUS = "data/status.json"
REG = "data/regimes.parquet"
EVENTS = "data/events.csv"
SCORE = "reports/live_scoreboard.md"

PAIR = {"type": "enum", "values": ["EURUSD", "USDCHF", "GBPUSD"]}
WINDOW = {"type": "enum", "values": ["30d", "90d", "1y", "5y"]}
FROM_USER = {"type": "from_user"}


def card(
    cid,
    tier,
    family,
    primitive,
    *,
    args=None,
    bindings=None,
    owner=PACK,
    en=(),
    de=(),
    fr=(),
    cap="",
    aria="",
    when_not="",
    rivals=(),
    rule="",
    status="built",
):
    return {
        "id": cid,
        "status": status,
        "tier": tier,
        "family": family,
        "primitive": primitive,
        "question_intents": {"en": list(en), "de": list(de), "fr": list(fr)},
        "args": args or {},
        "bindings": bindings or {},
        "disambiguation": {"rivals": list(rivals), "rule": rule or "no near neighbour"},
        "caption": {"en": cap},
        "aria": {"en": aria or cap},
        "when_not": when_not,
        "owner_artifact": owner,
    }


CARDS = [
    # ---- Family A — state ---------------------------------------------------------------------
    card(
        "condition_card",
        1,
        "state",
        "stat_block",
        args={"pair": PAIR},
        bindings={
            "word": "pack.pairs.{pair}.regime",
            "risk": "pack.pairs.{pair}.change_risk_5d",
            "lo": "pack.pairs.{pair}.risk_lo",
            "hi": "pack.pairs.{pair}.risk_hi",
            "siren": "pack.pairs.{pair}.anomaly_pct",
        },
        en=[
            "how does {pair} look today",
            "what is the regime",
            "is it calm right now",
            "current conditions",
            "give me today's read",
            "how are things",
        ],
        de=["wie sieht {pair} heute aus", "wie ist das regime", "ist es gerade ruhig"],
        fr=["comment se présente {pair} aujourd'hui", "quel est le régime", "est-ce calme"],
        cap="{pair} · {word} · change risk {risk} (band {lo} to {hi}) · siren {siren}",
        aria="Condition for {pair}: {word}, change risk {risk}, band {lo} to {hi}",
        rivals=["regime_probability_bars", "siren_gauge"],
        rule="word first; probabilities only if the user asks how sure; gauge only for unusualness",
        when_not="user asked about history, money impact, or methodology",
    ),
    card(
        "consensus_dots",
        1,
        "state",
        "dot_row",
        args={"pair": PAIR},
        bindings={
            "votes": "pack.pairs.{pair}.agreement",
            "text": "pack.pairs.{pair}.consensus_text",
        },
        en=[
            "do the models agree",
            "what is the consensus",
            "how many voters see stress",
            "is there agreement",
            "do your detectors agree",
        ],
        de=["sind sich die modelle einig", "wie ist der konsens"],
        fr=["les modèles sont-ils d'accord", "quel est le consensus"],
        cap="Stress consensus for {pair}: {votes} of 3 voters",
        aria="Consensus for {pair}: {votes} of 3 stress voters agree",
        rivals=["condition_card"],
        rule="dots only when the question is about agreement",
        when_not="user asked for the overall condition",
    ),
    card(
        "regime_probability_bars",
        2,
        "state",
        "bar_row",
        args={"pair": PAIR},
        bindings={"probs": "series.regime_probs.{pair}", "word": "pack.pairs.{pair}.regime"},
        en=[
            "how sure are you it is calm",
            "what are the regime probabilities",
            "how confident is the model",
            "probability of each regime",
            "how certain",
        ],
        de=["wie sicher ist das", "wie sind die regime wahrscheinlichkeiten"],
        fr=["quelle est votre certitude", "probabilités des régimes"],
        cap="{pair} regime probabilities · {word} leads",
        aria="Regime probabilities for {pair}, {word} leads",
        rivals=["condition_card"],
        rule="bars only when the user asks how sure or for probabilities",
        when_not="user asked what the regime is",
    ),
    card(
        "siren_gauge",
        2,
        "state",
        "stat_block",
        args={"pair": PAIR},
        bindings={"siren": "pack.pairs.{pair}.anomaly_pct"},
        en=[
            "how unusual is today",
            "what is the siren",
            "is today strange",
            "anomaly reading",
            "how weird is today",
        ],
        de=["wie ungewöhnlich ist heute", "wie hoch ist die sirene"],
        fr=["à quel point aujourd'hui est inhabituel", "niveau de la sirène"],
        cap="Siren for {pair}: {siren} of 100",
        aria="Siren for {pair} is {siren} out of 100",
        rivals=["condition_card"],
        rule="gauge only when the question is about unusualness",
        when_not="user asked for the regime or the change risk",
    ),
    card(
        "pair_compare_table",
        1,
        "state",
        "table",
        args={"pairs": {"type": "enum_list", "values": PAIR["values"]}},
        bindings={"rows": "table.pair_compare"},
        en=[
            "which pair is calmest",
            "compare the pairs",
            "how do the markets compare",
            "show me all pairs",
            "which market is quietest",
        ],
        de=["welches paar ist am ruhigsten", "vergleiche die paare"],
        fr=["quelle paire est la plus calme", "comparer les paires"],
        cap="Today across the markets: regime, change risk and siren side by side",
        aria="Comparison table of markets by regime, change risk and siren",
        rivals=["condition_card"],
        rule="table when more than one market is named or compared",
        when_not="user named exactly one market",
    ),
    card(
        "drift_status",
        2,
        "state",
        "stat_block",
        args={},
        bindings={"stale": "pack.drift.model_stale", "days": "pack.ledger.days_live"},
        owner=STATUS,
        en=[
            "is the model still healthy",
            "has anything drifted",
            "is the model stale",
            "model health",
            "are your models still valid",
        ],
        de=["ist das modell noch gesund", "gibt es drift"],
        fr=["le modèle est-il toujours valide", "y a-t-il une dérive"],
        cap="Model health: stale={stale} · live for {days} days",
        aria="Model health, stale flag {stale}, live for {days} days",
        when_not="user asked about forecast accuracy — use the scoreboard",
    ),
    # ---- Family B — time and history -----------------------------------------------------------
    card(
        "risk_trace",
        1,
        "time",
        "trace_band",
        args={"pair": PAIR, "window": WINDOW},
        bindings={
            "points": "series.risk.{pair}.{window}",
            "risk": "pack.pairs.{pair}.change_risk_5d",
        },
        en=[
            "how has risk moved",
            "show me the risk over time",
            "risk history",
            "has change risk been rising",
            "risk trend",
            "plot the change risk",
        ],
        de=["wie hat sich das risiko entwickelt", "zeige den risikoverlauf"],
        fr=["comment le risque a évolué", "historique du risque"],
        cap="{pair} change risk over {window}, with its conformal band · now {risk}",
        aria="Change risk trace for {pair} over {window}, currently {risk}",
        rivals=["vol_trace"],
        rule="risk unless the user says the word volatility",
        when_not="user asked about volatility specifically",
    ),
    card(
        "regime_timeline_ribbon",
        1,
        "time",
        "ribbon",
        args={"pair": PAIR, "window": WINDOW},
        bindings={
            "segments": "series.regime.{pair}.{window}",
            "days": "pack.pairs.{pair}.days_in_regime",
        },
        en=[
            "how long in this regime",
            "show me the regime history",
            "regime timeline",
            "when did it change",
            "how long has it been calm",
        ],
        de=["wie lange schon in diesem regime", "zeige die regime historie"],
        fr=["depuis combien de temps ce régime", "chronologie des régimes"],
        cap="{pair} regimes over {window} · day {days} of the current one",
        aria="Regime timeline for {pair} over {window}, day {days} of the current regime",
        rivals=["regime_history_table"],
        rule="ribbon for the shape, table when they ask for dates",
        when_not="user asked for specific dates",
    ),
    card(
        "regime_history_table",
        2,
        "time",
        "table",
        args={"pair": PAIR},
        bindings={"rows": "table.regime_history.{pair}"},
        en=[
            "when was the last crisis",
            "list the past regimes",
            "regime dates",
            "history of storms",
            "when did the last crisis start",
        ],
        de=["wann war die letzte krise", "liste der vergangenen regime"],
        fr=["quand était la dernière crise", "liste des régimes passés"],
        cap="{pair}: past regime episodes with start dates and lengths",
        aria="Table of past regime episodes for {pair}",
        rivals=["regime_timeline_ribbon"],
        rule="table when the user asks when or for dates",
        when_not="user wanted the visual shape of history",
    ),
    card(
        "period_compare_card",
        2,
        "time",
        "stat_block",
        args={
            "pair": PAIR,
            "anchor": {"type": "enum", "values": ["week", "month", "quarter", "year"]},
        },
        bindings={
            "now": "pack.pairs.{pair}.change_risk_5d",
            "then": "series.anchor.{pair}.{anchor}",
        },
        en=[
            "versus last month",
            "how does this compare to last week",
            "compared to a year ago",
            "is this worse than before",
            "change since last quarter",
        ],
        de=["im vergleich zum letzten monat", "wie war es letzte woche"],
        fr=["par rapport au mois dernier", "comparé à la semaine dernière"],
        cap="{pair} change risk now {now} versus {anchor} ago {then}",
        aria="Change risk for {pair} now {now} against {then} a {anchor} ago",
        when_not="user asked only about today",
    ),
    card(
        "vol_trace",
        2,
        "time",
        "trace_band",
        args={"pair": PAIR, "window": WINDOW},
        bindings={"points": "series.vol.{pair}.{window}"},
        en=[
            "is volatility rising",
            "show me volatility",
            "how volatile is it",
            "volatility trend",
            "has vol picked up",
        ],
        de=["steigt die volatilität", "zeige die volatilität"],
        fr=["la volatilité augmente-t-elle", "montre la volatilité"],
        cap="{pair} realised volatility over {window}",
        aria="Realised volatility trace for {pair} over {window}",
        rivals=["risk_trace"],
        rule="volatility only when the user says volatility or vol",
        when_not="user asked about change risk",
    ),
    card(
        "regime_duration_stats",
        3,
        "time",
        "bar_row",
        args={"pair": PAIR},
        status="planned",
        bindings={"rows": "table.regime_durations.{pair}"},
        en=["how long do storms last", "typical regime length", "average crisis duration"],
        de=["wie lange dauern stürme"],
        fr=["combien de temps durent les tempêtes"],
        cap="{pair}: typical length of each regime",
        aria="Typical regime durations for {pair}",
        when_not="user asked about the current regime only",
    ),
    card(
        "what_changed_card",
        2,
        "time",
        "stat_block",
        args={"pair": PAIR},
        bindings={
            "word": "pack.pairs.{pair}.regime",
            "risk": "pack.pairs.{pair}.change_risk_5d",
            "delta": "series.delta.{pair}",
        },
        en=[
            "what changed since yesterday",
            "anything new",
            "what moved",
            "what is different today",
            "any change",
        ],
        de=["was hat sich seit gestern geändert", "gibt es neues"],
        fr=["qu'est-ce qui a changé depuis hier", "quoi de neuf"],
        cap="{pair} since yesterday: {word}, change risk {risk} ({delta})",
        aria="What changed for {pair} since yesterday: {word}, change risk {risk}, moved {delta}",
        when_not="user asked for a longer history",
    ),
]

CARDS += [
    # ---- Family C — decision and money ---------------------------------------------------------
    card(
        "treasury_light",
        1,
        "decision",
        "stat_block",
        args={"pair": PAIR},
        owner=TRE,
        bindings={
            "light": "treasury.pairs.{pair}.light",
            "why": "treasury.pairs.{pair}.light_reason",
            "word": "pack.pairs.{pair}.regime",
        },
        en=[
            "hedge wait or ladder",
            "what should I consider",
            "what is the light",
            "should I do something",
            "what does the traffic light say",
            "hedge or wait",
        ],
        de=["absichern warten oder staffeln", "was sagt die ampel"],
        fr=["couvrir attendre ou échelonner", "que dit le feu"],
        cap="{pair}: the light is {light} — {why}",
        aria="Treasury light for {pair} is {light}, because {why}",
        rivals=["scenario_ladder", "exposure_calculator"],
        rule="light when they ask what to consider; ladder when they name a move; calculator when they name an amount",
        when_not="user named a specific amount or move",
    ),
    card(
        "var_es_bars",
        1,
        "decision",
        "bar_row",
        args={
            "pair": PAIR,
            "metric": {"type": "enum", "values": ["var_99", "var_95", "es_99", "es_95"]},
        },
        owner=TRE,
        bindings={
            "rows": "table.var_es.{pair}.{metric}",
            "regime": "treasury.pairs.{pair}.current_regime",
        },
        en=[
            "how bad is a bad week",
            "what is the value at risk",
            "worst case week",
            "expected shortfall",
            "how much could I lose in a week",
            "downside risk",
        ],
        de=["wie schlimm ist eine schlechte woche", "was ist der value at risk"],
        fr=["à quel point une mauvaise semaine", "quelle est la valeur en risque"],
        cap="{pair} {metric} by regime · today's regime is {regime}",
        aria="Value at risk bars for {pair}, metric {metric}, current regime {regime}",
        rivals=["impact_waterfall", "exposure_calculator"],
        rule="bars for the risk numbers themselves; calculator once an exposure amount is given",
        when_not="user gave an amount — use the calculator",
    ),
    card(
        "exposure_calculator",
        1,
        "decision",
        "stat_block",
        args={
            "pair": PAIR,
            "exposure": FROM_USER,
            "tolerance": {"type": "enum", "values": ["conservative", "balanced", "aggressive"]},
        },
        owner=DEC,
        bindings={
            "ratio": "decision.pairs.{pair}.{tolerance}.hedge_ratio",
            "es": "decision.pairs.{pair}.{tolerance}.es_99_1w",
            "light": "decision.pairs.{pair}.{tolerance}.light",
        },
        en=[
            "what about my 800000 euros",
            "I have an exposure",
            "for my position",
            "what does that mean for my amount",
            "size it for me",
            "my exposure is",
        ],
        de=["was bedeutet das für meine 800000 euro", "für meine position"],
        fr=["et pour mes 800000 euros", "pour ma position"],
        cap="Cover {ratio} of the exposure · uncovered one-week expected shortfall {es} · light {light}",
        aria="For your exposure: cover {ratio}, uncovered expected shortfall {es}, light {light}",
        rivals=["treasury_light", "scenario_ladder"],
        rule="calculator only when the user states an amount",
        when_not="no amount was given",
    ),
    card(
        "scenario_ladder",
        1,
        "decision",
        "stat_block",
        args={"pair": PAIR, "move": FROM_USER},
        owner=TRE,
        bindings={
            "rows": "table.scenario.{pair}",
            "regime": "treasury.pairs.{pair}.current_regime",
        },
        en=[
            "what if it moves 3 percent",
            "what happens if it drops",
            "if the rate moves",
            "scenario for a move",
            "what if it shifts",
        ],
        de=["was wenn es sich um 3 prozent bewegt", "szenario für eine bewegung"],
        fr=["et si ça bouge de 3 pour cent", "scénario de mouvement"],
        cap="{pair}: a move of the stated size against the historical record for {regime} conditions",
        aria="Scenario for {pair} for the stated move, current regime {regime}",
        rivals=["move_frequency_bars", "impact_waterfall"],
        rule="ladder when they name a move; frequency when they ask how often; waterfall for the money breakdown",
        when_not="user asked how often such moves happen",
    ),
    card(
        "impact_waterfall",
        2,
        "decision",
        "bar_row",
        args={"pair": PAIR, "move": FROM_USER},
        owner=TRE,
        bindings={"rows": "table.impact.{pair}"},
        en=[
            "show me the damage",
            "break down the impact",
            "where does the loss come from",
            "impact breakdown",
            "what would it cost me",
        ],
        de=["zeig mir den schaden", "aufschlüsselung der auswirkung"],
        fr=["montre-moi les dégâts", "détail de l impact"],
        cap="{pair}: where the impact of the stated move lands",
        aria="Impact breakdown for {pair} for the stated move",
        rivals=["scenario_ladder"],
        rule="waterfall only when they ask to break the number down",
        when_not="user only asked what happens, not why",
    ),
    card(
        "move_frequency_bars",
        1,
        "decision",
        "bar_row",
        args={
            "pair": PAIR,
            "size_band": {"type": "enum", "values": ["1pct", "2pct", "3pct", "5pct"]},
        },
        bindings={"rows": "table.move_frequency.{pair}.{size_band}"},
        owner=REG,
        en=[
            "how often does that happen",
            "how common is a 3 percent move",
            "frequency of moves",
            "has that happened before",
            "how rare is that",
        ],
        de=["wie oft passiert das", "wie häufig ist eine solche bewegung"],
        fr=["à quelle fréquence cela arrive", "est-ce fréquent"],
        cap="{pair}: how often moves of that size occurred in the record",
        aria="Historical frequency of moves of the stated size for {pair}",
        rivals=["scenario_ladder"],
        rule="frequency when the question contains how often or how common",
        when_not="user asked what a move would cost",
    ),
    card(
        "hedge_compare_table",
        2,
        "decision",
        "table",
        args={"pair": PAIR},
        owner=DEC,
        bindings={"rows": "table.hedge_compare.{pair}"},
        en=[
            "forward versus ladder versus nothing",
            "compare hedging approaches",
            "what are my options",
            "which hedge structure",
            "hedge alternatives",
        ],
        de=["termin gegen staffel gegen nichts", "vergleiche absicherungen"],
        fr=["terme contre échelonnement contre rien", "comparer les couvertures"],
        cap="{pair}: three mechanical approaches, and what each leaves uncovered",
        aria="Comparison of hedging approaches for {pair}",
        rivals=["treasury_light"],
        rule="table when they ask to compare structures",
        when_not="user asked what to do rather than what the options are",
    ),
    card(
        "cost_of_waiting_curve",
        2,
        "decision",
        "trace_band",
        args={"pair": PAIR},
        owner=TRE,
        bindings={"points": "series.cost_of_waiting.{pair}"},
        en=[
            "what does another month cost",
            "cost of waiting",
            "if I delay",
            "price of postponing",
            "what if I wait",
        ],
        de=["was kostet ein weiterer monat", "kosten des wartens"],
        fr=["combien coûte un mois de plus", "coût de l attente"],
        cap="{pair}: uncovered expected shortfall as the horizon lengthens",
        aria="Cost of waiting curve for {pair} across horizons",
        when_not="user asked about today only",
    ),
    card(
        "breakeven_rate_card",
        3,
        "decision",
        "stat_block",
        args={"pair": PAIR},
        status="planned",
        owner=TRE,
        bindings={"rate": "table.breakeven.{pair}"},
        en=["at what rate do I break even", "breakeven rate", "where is my break even"],
        de=["bei welchem kurs ist der break even"],
        fr=["à quel taux suis-je à l équilibre"],
        cap="{pair}: the rate at which the hedge and the exposure offset",
        aria="Breakeven rate for {pair}",
        when_not="user asked about risk rather than a rate",
    ),
    card(
        "hedge_ladder_plan",
        3,
        "decision",
        "table",
        args={"pair": PAIR, "horizon": {"type": "enum", "values": ["1", "2", "4", "8", "12"]}},
        status="planned",
        owner=DEC,
        bindings={"rows": "decision.pairs.{pair}.balanced.schedule_by_horizon.{horizon}"},
        en=["how would I tranche it", "ladder plan", "split it over weeks"],
        de=["wie würde ich es staffeln"],
        fr=["comment échelonner"],
        cap="{pair}: tranche schedule over {horizon} weeks",
        aria="Tranche schedule for {pair} over {horizon} weeks",
        when_not="user has not decided to hedge",
    ),
    # ---- Family D — trust and evidence ---------------------------------------------------------
    card(
        "scoreboard_card",
        1,
        "trust",
        "stat_block",
        args={},
        bindings={
            "days": "pack.ledger.days_live",
            "live": "pack.ledger.live_brier",
            "frozen": "pack.ledger.frozen_brier",
            "head": "pack.ledger.chain_head_short",
        },
        en=[
            "why should I trust you",
            "what is your track record",
            "how accurate are you",
            "show me your record",
            "are you any good",
            "your scoreboard",
        ],
        de=["warum sollte ich ihnen vertrauen", "wie ist ihre bilanz"],
        fr=["pourquoi vous faire confiance", "quel est votre historique"],
        cap="Live for {days} days · live Brier {live} against frozen {frozen} · chain {head}",
        aria="Track record: {days} days live, live Brier {live} versus frozen {frozen}",
        rivals=["coverage_plot", "chain_verify_card"],
        rule="scoreboard unless the word is bands, coverage or verify",
        when_not="user asked specifically about band coverage or verification",
    ),
    card(
        "coverage_plot",
        2,
        "trust",
        "trace_band",
        args={},
        bindings={"points": "series.coverage", "live": "pack.ledger.coverage_live"},
        en=[
            "are your bands honest",
            "what is your coverage",
            "do the intervals hold",
            "band coverage",
            "are the bands calibrated",
        ],
        de=["sind ihre bänder ehrlich", "wie ist die abdeckung"],
        fr=["vos bandes sont-elles honnêtes", "quelle est la couverture"],
        cap="Conformal coverage over time · live {live} against the 0.9 target",
        aria="Coverage plot, live coverage {live} against the target",
        rivals=["scoreboard_card"],
        rule="coverage only when the word is bands or coverage",
        when_not="user asked about accuracy generally",
    ),
    card(
        "ledger_row_receipt",
        1,
        "trust",
        "table",
        args={"date": {"type": "key", "source": "ledger_dates"}},
        bindings={"rows": "table.ledger_row.{date}"},
        owner=SCORE,
        en=[
            "show me an actual sealed row",
            "show me a ledger entry",
            "one real forecast",
            "prove a forecast was sealed",
            "show a receipt",
        ],
        de=["zeig mir einen versiegelten eintrag", "ein echter ledger eintrag"],
        fr=["montre une ligne scellée", "une vraie prévision"],
        cap="One sealed ledger row from {date}, exactly as written before the outcome existed",
        aria="Sealed ledger row for {date}",
        rivals=["chain_verify_card"],
        rule="receipt shows a row; verify card shows how to check it",
        when_not="user asked how to verify rather than to see one",
    ),
    card(
        "chain_verify_card",
        2,
        "trust",
        "stat_block",
        args={},
        bindings={
            "head": "pack.ledger.chain_head_short",
            "ok": "pack.ledger.chain_ok",
            "n": "pack.ledger.n_forecasts",
        },
        en=[
            "how do I verify it myself",
            "can I check the chain",
            "how do I audit this",
            "verify independently",
            "prove it to me",
        ],
        de=["wie kann ich das selbst prüfen", "wie verifiziere ich die kette"],
        fr=["comment vérifier moi-même", "comment auditer"],
        cap="Chain head {head} · {n} forecasts · verifier says chain_ok={ok}",
        aria="Chain verification: head {head}, {n} forecasts, chain valid {ok}",
        rivals=["ledger_row_receipt"],
        rule="verify card when the user asks how to check",
        when_not="user asked to see a row",
    ),
    card(
        "direction_evidence_card",
        1,
        "trust",
        "stat_block",
        args={},
        bindings={"days": "pack.ledger.days_live"},
        en=[
            "can anyone predict price",
            "will it go up",
            "where is the rate heading",
            "what is your forecast for the price",
            "can you predict direction",
            "buy or sell",
        ],
        de=["kann jemand den preis vorhersagen", "steigt es"],
        fr=["peut-on prévoir le prix", "va-t-il monter"],
        cap="This system models conditions and risk, never direction — and the record shows why that is the honest position",
        aria="Direction evidence: this system does not model price direction",
        rivals=["scoreboard_card"],
        rule="always this card for any direction question, before any other",
        when_not="never suppressed — direction questions always land here",
    ),
    card(
        "calibration_curve",
        3,
        "trust",
        "trace_band",
        args={},
        status="planned",
        bindings={"points": "series.calibration"},
        en=["are your probabilities real", "show the calibration curve", "reliability diagram"],
        de=["sind ihre wahrscheinlichkeiten echt"],
        fr=["vos probabilités sont-elles fiables"],
        cap="Calibration: predicted probability against realised frequency",
        aria="Calibration curve",
        when_not="user asked about coverage instead",
    ),
    card(
        "model_version_card",
        3,
        "trust",
        "table",
        args={},
        status="planned",
        bindings={"rows": "table.model_versions"},
        owner=STATUS,
        en=["what is running right now", "which model version", "what is deployed"],
        de=["welche version läuft"],
        fr=["quelle version tourne"],
        cap="Deployed model versions and their frozen dates",
        aria="Model version table",
        when_not="user asked about accuracy",
    ),
    card(
        "champion_challenger_card",
        3,
        "trust",
        "table",
        args={"slot": {"type": "enum", "values": ["regime", "forecaster"]}},
        status="planned",
        bindings={"rows": "table.champion_challenger.{slot}"},
        owner=SCORE,
        en=["which model is winning", "champion versus challenger", "is the challenger better"],
        de=["welches modell gewinnt"],
        fr=["quel modèle gagne"],
        cap="Champion against challenger in the {slot} slot, scored on sealed rows",
        aria="Champion challenger comparison for the {slot} slot",
        when_not="user asked about the shipped record only",
    ),
]

CARDS += [
    # ---- Family E — context and drivers --------------------------------------------------------
    card(
        "event_countdown_strip",
        1,
        "context",
        "dot_row",
        args={},
        owner=EVENTS,
        bindings={"events": "pack.events"},
        en=[
            "what is coming up",
            "any events this week",
            "when is the next central bank meeting",
            "what is on the calendar",
            "upcoming events",
            "when is the fed",
        ],
        de=["was steht an", "wann ist die nächste notenbanksitzung"],
        fr=["qu est-ce qui arrive", "prochaine réunion de banque centrale"],
        cap="Scheduled events ahead, nearest first",
        aria="Countdown strip of scheduled economic events",
        rivals=["event_study_card"],
        rule="strip for what is coming; study for what usually happens",
        when_not="user asked what typically happens around an event",
    ),
    card(
        "feature_driver_bars",
        1,
        "context",
        "bar_row",
        args={"pair": PAIR},
        bindings={"rows": "table.drivers.{pair}"},
        owner=REG,
        en=[
            "why is risk elevated",
            "what is driving this",
            "which features matter",
            "why that number",
            "what pushed the risk up",
            "explain the drivers",
        ],
        de=["warum ist das risiko erhöht", "was treibt das"],
        fr=["pourquoi le risque est élevé", "qu est-ce qui explique cela"],
        cap="{pair}: what contributed most to today's change risk",
        aria="Feature drivers behind the change risk for {pair}",
        rivals=["methodology_flow"],
        rule="drivers for today's number; flow for how the metric is built",
        when_not="user asked how the metric is computed in general",
    ),
    card(
        "cross_asset_card",
        2,
        "context",
        "table",
        args={},
        bindings={"rows": "table.cross_asset"},
        owner=REG,
        en=[
            "what is the wider market doing",
            "how are other assets",
            "cross asset picture",
            "what about equities and rates",
            "broader market",
        ],
        de=["was macht der breitere markt", "wie stehen andere anlagen"],
        fr=["que fait le marché plus large", "vue multi-actifs"],
        cap="The wider market context alongside the currency read",
        aria="Cross asset context table",
        when_not="user asked about one currency pair only",
    ),
    card(
        "event_study_card",
        2,
        "context",
        "bar_row",
        args={
            "event_type": {"type": "enum", "values": ["FOMC", "ECB", "SNB", "BOE", "NFP", "CPI"]}
        },
        bindings={"rows": "table.event_study.{event_type}"},
        owner=EVENTS,
        en=[
            "what usually happens around snb",
            "typical behaviour around the fed",
            "how do markets behave on cpi days",
            "event study",
            "what happens around ecb",
        ],
        de=["was passiert üblicherweise um die snb", "typisches verhalten um die ezb"],
        fr=["que se passe-t-il autour de la bns", "étude d événement"],
        cap="What conditions typically did around {event_type} in the record",
        aria="Event study for {event_type}",
        rivals=["event_countdown_strip"],
        rule="study when the user asks what usually happens",
        when_not="user asked when the next one is",
    ),
    card(
        "positioning_card",
        3,
        "context",
        "stat_block",
        args={},
        status="planned",
        bindings={"value": "table.positioning"},
        en=["how is everyone positioned", "what is the market positioning", "crowding"],
        de=["wie ist die positionierung"],
        fr=["quel est le positionnement"],
        cap="Aggregate positioning context",
        aria="Positioning card",
        when_not="no positioning artifact is published",
    ),
    card(
        "policy_tone_card",
        3,
        "context",
        "trace_band",
        args={"bank": {"type": "enum", "values": ["FED", "ECB", "SNB", "BOE"]}},
        status="planned",
        bindings={"points": "series.policy_tone.{bank}"},
        en=["have central banks turned", "policy tone", "is the tone changing"],
        de=["hat sich der ton geändert"],
        fr=["le ton a-t-il changé"],
        cap="Communication tone index for {bank} over time",
        aria="Policy tone trace for {bank}",
        when_not="user asked about a scheduled meeting",
    ),
    card(
        "uncertainty_index_card",
        3,
        "context",
        "trace_band",
        args={},
        status="planned",
        bindings={"points": "series.uncertainty"},
        en=["is macro uncertainty high", "uncertainty index", "how uncertain is the macro picture"],
        de=["ist die makro unsicherheit hoch"],
        fr=["l incertitude macro est-elle élevée"],
        cap="Macro uncertainty index over time",
        aria="Macro uncertainty index",
        when_not="user asked about one market",
    ),
    # ---- Family F — story and media ------------------------------------------------------------
    card(
        "storm_replay_mini",
        1,
        "story",
        "ribbon",
        args={"episode": {"type": "key", "source": "episodes"}},
        bindings={"segments": "series.storm.{episode}"},
        owner=REG,
        en=[
            "how did covid look",
            "show me a past storm",
            "what did 2008 look like",
            "replay a crisis",
            "show me march 2020",
        ],
        de=["wie sah covid aus", "zeige einen vergangenen sturm"],
        fr=["à quoi ressemblait le covid", "montre une tempête passée"],
        cap="{episode}: how the regimes moved through the episode",
        aria="Storm replay ribbon for {episode}",
        rivals=["storm_compare_card", "storm_replay_player"],
        rule="mini for the shape; compare only when today is referenced; player when they ask day by day",
        when_not="user compared it to today",
    ),
    card(
        "storm_replay_player",
        2,
        "story",
        "media_frame",
        args={"episode": {"type": "key", "source": "episodes"}},
        bindings={"src": "media.storm.{episode}"},
        owner=REG,
        en=[
            "show me day by day",
            "play the replay",
            "walk me through it",
            "step through the crisis",
            "play it",
        ],
        de=["zeig es tag für tag", "spiel die wiederholung"],
        fr=["montre jour par jour", "lance la relecture"],
        cap="{episode}, day by day",
        aria="Storm replay player for {episode}",
        rivals=["storm_replay_mini"],
        rule="player only when they ask to step through or play",
        when_not="a still ribbon answers the question",
    ),
    card(
        "storm_compare_card",
        2,
        "story",
        "table",
        args={"pair": PAIR, "episode": {"type": "key", "source": "episodes"}},
        bindings={"rows": "table.storm_compare.{pair}.{episode}"},
        owner=REG,
        en=[
            "is today like march 2023",
            "compare today to a past crisis",
            "does this look like 2008",
            "is this similar to covid",
            "compare with history",
        ],
        de=["ist heute wie märz 2023", "vergleiche heute mit einer krise"],
        fr=["est-ce comme mars 2023", "comparer avec une crise passée"],
        cap="{pair} today against {episode}, metric by metric",
        aria="Comparison of today against {episode} for {pair}",
        rivals=["storm_replay_mini"],
        rule="compare only when today is referenced",
        when_not="user asked only about the past episode",
    ),
    card(
        "weekly_briefing_clip",
        2,
        "story",
        "media_frame",
        args={"week": {"type": "key", "source": "weeks"}},
        bindings={"src": "media.weekly.{week}"},
        owner="docs/weekly",
        en=[
            "give me the weekly briefing",
            "the weekly report",
            "this week's summary",
            "weekly video",
            "monday briefing",
        ],
        de=["gib mir das wochenbriefing", "der wochenbericht"],
        fr=["le briefing hebdomadaire", "le rapport de la semaine"],
        cap="The briefing published for week {week}",
        aria="Weekly briefing clip for week {week}",
        when_not="user asked about today only",
    ),
    card(
        "milestone_card",
        3,
        "story",
        "stat_block",
        args={},
        status="planned",
        bindings={"days": "pack.ledger.days_live"},
        en=["how long have you been live", "when did you start", "project milestones"],
        de=["wie lange sind sie schon live"],
        fr=["depuis quand êtes-vous en ligne"],
        cap="Live for {days} days",
        aria="Milestone card, live for {days} days",
        when_not="user asked about accuracy",
    ),
    card(
        "snapshot_export_card",
        2,
        "story",
        "media_frame",
        args={"board_id": {"type": "key", "source": "boards"}},
        bindings={"src": "media.snapshot.{board_id}"},
        en=[
            "send this to my cfo",
            "export this",
            "can I share this",
            "give me a snapshot",
            "save this view",
        ],
        de=["schick das an meinen cfo", "exportiere das"],
        fr=["envoyer ceci à mon directeur financier", "exporter ceci"],
        cap="A snapshot of this board, with its as-of stamp and chain head",
        aria="Snapshot export of the current board",
        when_not="user asked a data question",
    ),
    # ---- Family G — explain and escalate -------------------------------------------------------
    card(
        "explainer_diagram",
        1,
        "explain",
        "diagram_frame",
        args={
            "diagram": {
                "type": "enum",
                "values": ["siren", "regime", "conformal", "ledger", "consensus", "pipeline"],
            }
        },
        bindings={"svg": "diagram.{diagram}"},
        owner="docs/diagrams",
        en=[
            "how does the siren work",
            "explain the model",
            "how does it work",
            "show me how this works",
            "explain the pipeline",
            "how is the regime found",
        ],
        de=["wie funktioniert die sirene", "erkläre das modell"],
        fr=["comment fonctionne la sirène", "expliquez le modèle"],
        cap="How {diagram} works, end to end",
        aria="Explainer diagram for {diagram}",
        rivals=["methodology_flow", "glossary_card"],
        rule="diagram for how it works; flow for where one number comes from; glossary for one word",
        when_not="user asked for the definition of a single term",
    ),
    card(
        "glossary_card",
        1,
        "explain",
        "stat_block",
        args={
            "term": {
                "type": "enum",
                "values": [
                    "chop",
                    "calm",
                    "trend",
                    "crisis",
                    "siren",
                    "band",
                    "brier",
                    "consensus",
                    "filtered",
                    "ledger",
                ],
            }
        },
        bindings={"definition": "glossary.{term}"},
        owner="docs/avatar_knowledge.md",
        en=[
            "what does chop mean",
            "define the siren",
            "what is a regime",
            "what does that word mean",
            "explain the term",
            "what is filtered",
        ],
        de=["was bedeutet chop", "definiere die sirene"],
        fr=["que signifie chop", "définition de la sirène"],
        cap="{term}: {definition}",
        aria="Glossary definition of {term}",
        rivals=["explainer_diagram"],
        rule="glossary for one word; diagram when they ask how it works",
        when_not="user asked how the mechanism works",
    ),
    card(
        "methodology_flow",
        2,
        "explain",
        "diagram_frame",
        args={
            "metric": {
                "type": "enum",
                "values": ["change_risk", "siren", "regime", "band", "light"],
            }
        },
        bindings={"svg": "diagram.flow.{metric}"},
        owner="docs/diagrams",
        en=[
            "where does this number come from",
            "how is change risk computed",
            "what goes into that metric",
            "trace the number",
            "how do you calculate it",
        ],
        de=["woher kommt diese zahl", "wie wird das berechnet"],
        fr=["d où vient ce chiffre", "comment est-ce calculé"],
        cap="How {metric} is produced, from raw bars to the published value",
        aria="Methodology flow for {metric}",
        rivals=["explainer_diagram", "feature_driver_bars"],
        rule="flow for how a number is built; drivers for why today's value is what it is",
        when_not="user asked why today's value is high",
    ),
    card(
        "faq_card",
        2,
        "explain",
        "table",
        args={
            "topic": {
                "type": "enum",
                "values": ["pricing", "tiers", "alerts", "api", "data", "privacy"],
            }
        },
        bindings={"rows": "table.faq.{topic}"},
        owner="docs/avatar_knowledge.md",
        en=[
            "what do I get for 79 francs",
            "what are the tiers",
            "how much does it cost",
            "what is included",
            "pricing",
            "what do the alerts do",
        ],
        de=["was bekomme ich für 79 franken", "welche stufen gibt es"],
        fr=["que comprend l abonnement", "quels sont les paliers"],
        cap="{topic}: what is included, in plain terms",
        aria="Frequently asked questions about {topic}",
        when_not="user asked a market question",
    ),
    card(
        "ask_your_bank_card",
        1,
        "explain",
        "table",
        args={
            "topic": {"type": "enum", "values": ["forward", "option", "spread", "ladder", "policy"]}
        },
        bindings={"rows": "table.ask_bank.{topic}"},
        owner="docs/avatar_knowledge.md",
        en=[
            "should I buy dollars",
            "what should I do with my money",
            "give me advice",
            "what would you do",
            "should I invest",
            "tell me what to trade",
        ],
        de=["soll ich dollar kaufen", "was soll ich tun"],
        fr=["dois-je acheter des dollars", "que dois-je faire"],
        cap="Questions worth putting to your bank or adviser about {topic}",
        aria="Printable list of questions to ask your bank about {topic}",
        rivals=["treasury_light", "direction_evidence_card"],
        rule="escalation card for any personal advice request; direction card if the question is about which way",
        when_not="the question was about direction — that goes to the direction evidence card",
    ),
    card(
        "metric_table",
        1,
        "explain",
        "table",
        args={"metric_keys": {"type": "key_list", "source": "whitelisted_metrics"}},
        bindings={"rows": "table.metrics.{metric_keys}"},
        en=[
            "show me the numbers",
            "give me the metrics",
            "what are the values",
            "the data please",
            "list the figures",
            "show the table",
        ],
        de=["zeig mir die zahlen", "gib mir die kennzahlen"],
        fr=["montre les chiffres", "donne les mesures"],
        cap="The requested published values, with their as-of stamp",
        aria="Table of the requested metrics",
        rivals=["condition_card"],
        rule="catch-all: only when nothing else fits",
        when_not="a purpose-built card answers the question",
    ),
]


def main() -> None:
    ids = [c["id"] for c in CARDS]
    assert len(ids) == len(set(ids)), "duplicate card ids"
    doc = {
        "registry_version": REGISTRY_VERSION,
        "schema": "v3",
        "catalog": "docs/REGISTRY-50.md",
        "cards": CARDS,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# GENERATED ONCE by scripts/seed_visual_registry.py (phase 38); the YAML is now the\n"
        "# source of truth — edit entries here, and add golden questions before flipping a status.\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)
    )
    built = sum(1 for c in CARDS if c["status"] == "built")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(CARDS)} cards, {built} built, {len(CARDS)-built} planned"
    )
    for tier in (1, 2, 3):
        n = sum(1 for c in CARDS if c["tier"] == tier)
        print(f"  tier {tier}: {n}")


if __name__ == "__main__":
    main()
